-- MySQL Script generated by MySQL Workbench
-- Sun Sep 18 17:15:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema helloBank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema helloBank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helloBank` DEFAULT CHARACTER SET utf8 ;
USE `helloBank` ;

-- -----------------------------------------------------
-- Table `helloBank`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helloBank`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(35) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helloBank`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helloBank`.`contas` (
  `idconta` INT NOT NULL AUTO_INCREMENT,
  `numero_conta` INT(9) NOT NULL,
  `agencia` INT(4) NOT NULL,
  `saldo` DOUBLE NULL,
  `tipo_conta` VARCHAR(45) NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idconta`),
  UNIQUE INDEX `numero_conta_UNIQUE` (`numero_conta` ASC) VISIBLE,
  INDEX `fk_conta_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_conta_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `helloBank`.`clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helloBank`.`trasacaoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helloBank`.`trasacaoes` (
  `idtransacao` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  `conta_idconta` INT NOT NULL,
  PRIMARY KEY (`idtransacao`),
  INDEX `fk_trasacaoes_conta1_idx` (`conta_idconta` ASC) VISIBLE,
  CONSTRAINT `fk_trasacaoes_conta1`
    FOREIGN KEY (`conta_idconta`)
    REFERENCES `helloBank`.`contas` (`idconta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
